jobs:
  build:
    strategy:
      matrix:
        dotnet-version: ['9.0', '10.0-preview']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build \
          --build-arg DOTNET_VERSION=${{ matrix.dotnet-version }} \
          -t tsp-solver:${{ matrix.dotnet-version }} .