name: Multi-Version Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        dotnet: ['9.0', '10.0']  # Easy to add versions
        continue-on-error: true   # Don't fail if 10.0 isn't out yet
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}.x
      continue-on-error: true
    
    - name: Build with .NET ${{ matrix.dotnet }}
      run: |
        dotnet --version
        dotnet build TSP.sln
      continue-on-error: ${{ matrix.dotnet == '10.0' }}